env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - standard
overrides: [ ]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  '@emotion/jsx-import': 'error',
  'react/no-unknown-property': [ 'error', { ignore: [ 'css' ] } ],
  'react/prop-types': 'off',
  'semi': [ 'error', 'always' ],
  'comma-dangle': [ 'error', 'always-multiline' ],
  'quotes': [ 'error', 'single' ],
  'default-case': 'error',
  # comment when developing, uncomment when committing
  'no-unused-vars': [ 'error', { 'vars': 'all', 'args': 'all', 'ignoreRestSiblings': false, 'argsIgnorePattern': '^_' } ],
#   uncomment when developing, comment when committing
#  'spaced-comment': 'off',
#  'no-unused-vars': 'off',
#  'prefer-const': 'off',
}
plugins:
  - react
  - '@emotion'
settings:
  react:
    version: 'detect'
