name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-react-app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::542773719222:role/github-actions-role
          aws-region: us-east-1

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to S3
        run: aws s3 sync build/ s3://tiletogether-static-assets-bucket --delete
